# Generated by Django 4.2.30 on 2026-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_symptomsubmission_cycle_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsubmission',
            name='bleeding_days',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='symptomsubmission',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
    ]
