# Generated by Django 4.2.30 on 2026-07-17 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("api", "0003_alter_symptomsubmission_bleeding_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_free_tier",
        ),
        migrations.AddField(
            model_name="user",
            name="institutional_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="billing.institutionallicense",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_settlement_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("under_18", "Under-18 (discounted)"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
