# Generated by Django 5.0.9 on 2026-07-21 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_user_is_free_tier_user_institutional_license_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptomsubmission",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="symptomsubmission",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="symptomsubmission",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="symptomsubmission",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
