# Generated by Django 4.2.30 on 2026-07-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_guardian_consent_requested_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="symptomsubmission",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
